name: publish

on:
  push:
    tags:        
      - 'v*'

jobs:
  publish-burn-derive:
    uses: burn-rs/burn/.github/workflows/publish-template.yml@main
    with:
      crate: burn-derive
    secrets: inherit

  publish-burn-dataset:
    uses: burn-rs/burn/.github/workflows/publish-template.yml@main
    with:
      crate: burn-dataset
    secrets: inherit

  publish-burn-tensor-testgen:
    uses: burn-rs/burn/.github/workflows/publish-template.yml@main
    with:
      crate: burn-tensor-testgen
    secrets: inherit

  publish-burn-tensor:
    uses: burn-rs/burn/.github/workflows/publish-template.yml@main
    needs:
      - publish-burn-tensor-testgen
    with:
      crate: burn-tensor
    secrets: inherit

  publish-burn-autodiff:
    uses: burn-rs/burn/.github/workflows/publish-template.yml@main
    needs:
      - publish-burn-tensor
      - publish-burn-tensor-testgen
    with:
      crate: burn-autodiff
    secrets: inherit

  publish-burn-tch:
    uses: burn-rs/burn/.github/workflows/publish-template.yml@main
    needs:
      - publish-burn-tensor
      - publish-burn-autodiff
    with:
      crate: burn-tch
    secrets: inherit

  publish-burn-ndarray:
    uses: burn-rs/burn/.github/workflows/publish-template.yml@main
    needs:
      - publish-burn-tensor
      - publish-burn-autodiff
    with:
      crate: burn-ndarray
    secrets: inherit

  publish-burn:
    uses: burn-rs/burn/.github/workflows/publish-template.yml@main
    needs: 
      - publish-burn-derive
      - publish-burn-dataset
      - publish-burn-tensor
      - publish-burn-autodiff
      - publish-burn-ndarray
    with:
      crate: burn
    secrets: inherit
